/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("lessons").del();
  await knex("lessons").insert([
    {
      id: 1,
      rank_id: 1,
      type: "Bounding Box",
      difficulty: "Green",
      level: 1,
      lesson_number: 1,
      title: "Image annotation",
      description:
        "This is the first lesson of image annotation for Bounding Box Green 1",
      passed: false,
      unlocked: true,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 2,
      rank_id: 1,
      type: "Bounding Box",
      difficulty: "Green",
      level: 1,
      lesson_number: 2,
      title: "Image annotation II",
      description:
        "This is the second lesson of image annotation for Bounding Box Green 1",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 3,
      rank_id: 1,
      type: "Bounding Box",
      difficulty: "Green",
      level: 1,
      lesson_number: 3,
      title: "Advanced image annotation",
      description:
        "This is the third lesson for Bounding Box Green 1 about advanced image annotation",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 4,
      rank_id: 2,
      type: "Bounding Box",
      difficulty: "Green",
      level: 2,
      lesson_number: 1,
      title: "Drawing boxes",
      description:
        "This is the first lesson for Bounding Box Green 2 about drawing boxes",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 5,
      rank_id: 2,
      type: "Bounding Box",
      difficulty: "Green",
      level: 2,
      lesson_number: 2,
      title: "BBG2L2",
      description:
        "This is the second lesson for Bounding Box Green 2 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 6,
      rank_id: 2,
      type: "Bounding Box",
      difficulty: "Green",
      level: 2,
      lesson_number: 3,
      title: "BBG2L3",
      description:
        "This is the third lesson for Bounding Box Green 2 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 7,
      rank_id: 3,
      type: "Bounding Box",
      difficulty: "Green",
      level: 3,
      lesson_number: 1,
      title: "BBG3L1",
      description:
        "This is the first lesson for Bounding Box Green 3 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 8,
      rank_id: 3,
      type: "Bounding Box",
      difficulty: "Green",
      level: 3,
      lesson_number: 2,
      title: "BBG3L2",
      description:
        "This is the second lesson for Bounding Box Green 3 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 9,
      rank_id: 3,
      type: "Bounding Box",
      difficulty: "Green",
      level: 3,
      lesson_number: 3,
      title: "BBG3L3",
      description:
        "This is the third lesson for Bounding Box Green 3 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 10,
      rank_id: 4,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 1,
      title: "BBY1L1",
      description:
        "This is the first lesson for Bounding Box Yellow 1 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 11,
      rank_id: 4,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 2,
      title: "BBY1L2",
      description:
        "This is the second lesson for Bounding Box Yellow 1 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 12,
      rank_id: 4,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 3,
      title: "BBY1L3",
      description:
        "This is the third lesson for Bounding Box Yellow 1 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 13,
      rank_id: 5,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 2,
      lesson_number: 1,
      title: "Bounding Box Refinement",
      description: "Refining bounding boxes for better results.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 14,
      rank_id: 5,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 2,
      lesson_number: 2,
      title: "Handling Complex Objects",
      description: "Drawing bounding boxes for complex objects.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 15,
      rank_id: 5,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 2,
      lesson_number: 3,
      title: "Bounding Box Automation",
      description: "Automating the creation of bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 16,
      rank_id: 6,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 3,
      lesson_number: 1,
      title: "Advanced Bounding Box Techniques",
      description: "Mastering advanced techniques for bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 17,
      rank_id: 6,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 3,
      lesson_number: 2,
      title: "Bounding Box for Different Shapes",
      description: "Creating bounding boxes for various shapes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 18,
      rank_id: 6,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 3,
      lesson_number: 3,
      title: "Bounding Box Accuracy Improvement",
      description: "Improving the accuracy of bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 19,
      rank_id: 7,
      type: "Bounding Box",
      difficulty: "Red",
      level: 1,
      lesson_number: 1,
      title: "Bounding Box Essentials",
      description: "Learn the essentials of bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 20,
      rank_id: 7,
      type: "Bounding Box",
      difficulty: "Red",
      level: 1,
      lesson_number: 2,
      title: "Bounding Box Techniques",
      description: "Understanding various techniques for bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 21,
      rank_id: 7,
      type: "Bounding Box",
      difficulty: "Red",
      level: 1,
      lesson_number: 3,
      title: "Bounding Box Applications",
      description: "Applications of bounding boxes in real-world scenarios.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 22,
      rank_id: 8,
      type: "Bounding Box",
      difficulty: "Red",
      level: 2,
      lesson_number: 1,
      title: "Bounding Box Optimization",
      description: "Optimizing bounding boxes for better performance.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 23,
      rank_id: 8,
      type: "Bounding Box",
      difficulty: "Red",
      level: 2,
      lesson_number: 2,
      title: "Bounding Box Accuracy",
      description: "Ensuring accuracy in bounding box placement.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 24,
      rank_id: 8,
      type: "Bounding Box",
      difficulty: "Red",
      level: 2,
      lesson_number: 3,
      title: "Advanced Bounding Box Applications",
      description: "Applying advanced techniques in bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 25,
      rank_id: 9,
      type: "Bounding Box",
      difficulty: "Red",
      level: 3,
      lesson_number: 1,
      title: "Bounding Box Mastery",
      description: "Mastering the use of bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 26,
      rank_id: 9,
      type: "Bounding Box",
      difficulty: "Red",
      level: 3,
      lesson_number: 2,
      title: "Bounding Box Challenges",
      description: "Tackling complex bounding box challenges.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 27,
      rank_id: 9,
      type: "Bounding Box",
      difficulty: "Red",
      level: 3,
      lesson_number: 3,
      title: "Bounding Box Innovations",
      description: "Innovative uses of bounding boxes.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 28,
      rank_id: 10,
      type: "Semantic",
      difficulty: "Green",
      level: 1,
      lesson_number: 1,
      title: "Introduction to Semantic Segmentation",
      description: "Understanding the basics of semantic segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 29,
      rank_id: 10,
      type: "Semantic",
      difficulty: "Green",
      level: 1,
      lesson_number: 2,
      title: "Semantic Segmentation Techniques",
      description: "Learning various techniques used in semantic segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 30,
      rank_id: 10,
      type: "Semantic",
      difficulty: "Green",
      level: 1,
      lesson_number: 3,
      title: "Semantic Segmentation Applications",
      description: "Exploring real-world applications of semantic segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 31,
      rank_id: 11,
      type: "Semantic",
      difficulty: "Green",
      level: 2,
      lesson_number: 1,
      title: "Advanced Semantic Segmentation Techniques",
      description: "Mastering advanced techniques in semantic segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 32,
      rank_id: 11,
      type: "Semantic",
      difficulty: "Green",
      level: 2,
      lesson_number: 2,
      title: "Semantic Segmentation Challenges",
      description: "Challenges faced in semantic segmentation and how to overcome them.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 33,
      rank_id: 11,
      type: "Semantic",
      difficulty: "Green",
      level: 2,
      lesson_number: 3,
      title: "Semantic Segmentation Optimization",
      description: "Optimizing semantic segmentation models for better performance.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 34,
      rank_id: 12,
      type: "Semantic",
      difficulty: "Green",
      level: 3,
      lesson_number: 1,
      title: "Semantic Segmentation Mastery",
      description: "Mastering the art of semantic segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 35,
      rank_id: 12,
      type: "Semantic",
      difficulty: "Green",
      level: 3,
      lesson_number: 2,
      title: "Semantic Segmentation Innovations",
      description: "Exploring innovative uses of semantic segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 36,
      rank_id: 12,
      type: "Semantic",
      difficulty: "Green",
      level: 3,
      lesson_number: 3,
      title: "Semantic Segmentation in Autonomous Systems",
      description: "Understanding how semantic segmentation is used in autonomous systems.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 37,
      rank_id: 13,
      type: "Semantic",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 1,
      title: "Introduction to Semantic Labeling",
      description: "Understanding the basics of semantic labeling.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 38,
      rank_id: 13,
      type: "Semantic",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 2,
      title: "Semantic Labeling Techniques",
      description: "Learning various techniques used in semantic labeling.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 39,
      rank_id: 13,
      type: "Semantic",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 3,
      title: "Semantic Labeling Applications",
      description: "Exploring real-world applications of semantic labeling.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 40,
      rank_id: 14,
      type: "Semantic",
      difficulty: "Yellow",
      level: 2,
      lesson_number: 1,
      title: "Advanced Semantic Labeling Techniques",
      description: "Mastering advanced techniques in semantic labeling.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 41,
      rank_id: 14,
      type: "Semantic",
      difficulty: "Yellow",
      level: 2,
      lesson_number: 2,
      title: "Semantic Labeling Challenges",
      description: "Challenges faced in semantic labeling and how to overcome them.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 42,
      rank_id: 14,
      type: "Semantic",
      difficulty: "Yellow",
      level: 2,
      lesson_number: 3,
      title: "Semantic Labeling Optimization",
      description: "Optimizing semantic labeling models for better performance.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 43,
      rank_id: 15,
      type: "Semantic",
      difficulty: "Yellow",
      level: 3,
      lesson_number: 1,
      title: "Semantic Labeling Mastery",
      description: "Mastering the art of semantic labeling.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 44,
      rank_id: 15,
      type: "Semantic",
      difficulty: "Yellow",
      level: 3,
      lesson_number: 2,
      title: "Semantic Labeling Innovations",
      description: "Exploring innovative uses of semantic labeling.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 45,
      rank_id: 15,
      type: "Semantic",
      difficulty: "Yellow",
      level: 3,
      lesson_number: 3,
      title: "Semantic Labeling in Autonomous Systems",
      description: "Understanding how semantic labeling is used in autonomous systems.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
    },
    {
      id: 46,
      rank_id: 16,
      type: "Semantic",
      difficulty: "Red",
      level: 1,
      lesson_number: 1,
      title: "Introduction to Semantic Annotation",
      description: "Understanding the basics of semantic annotation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 47,
      rank_id: 16,
      type: "Semantic",
      difficulty: "Red",
      level: 1,
      lesson_number: 2,
      title: "Semantic Annotation Techniques",
      description: "Learning various techniques used in semantic annotation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 48,
      rank_id: 16,
      type: "Semantic",
      difficulty: "Red",
      level: 1,
      lesson_number: 3,
      title: "Semantic Annotation Applications",
      description: "Exploring real-world applications of semantic annotation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 49,
      rank_id: 17,
      type: "Semantic",
      difficulty: "Red",
      level: 2,
      lesson_number: 1,
      title: "Advanced Semantic Annotation Techniques",
      description: "Mastering advanced techniques in semantic annotation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 50,
      rank_id: 17,
      type: "Semantic",
      difficulty: "Red",
      level: 2,
      lesson_number: 2,
      title: "Semantic Annotation Challenges",
      description: "Challenges faced in semantic annotation and how to overcome them.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 51,
      rank_id: 17,
      type: "Semantic",
      difficulty: "Red",
      level: 2,
      lesson_number: 3,
      title: "Semantic Annotation Optimization",
      description: "Optimizing semantic annotation models for better performance.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 52,
      rank_id: 18,
      type: "Semantic",
      difficulty: "Red",
      level: 3,
      lesson_number: 1,
      title: "Semantic Annotation Mastery",
      description: "Mastering the art of semantic annotation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 53,
      rank_id: 18,
      type: "Semantic",
      difficulty: "Red",
      level: 3,
      lesson_number: 2,
      title: "Semantic Annotation Innovations",
      description: "Exploring innovative uses of semantic annotation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 54,
      rank_id: 18,
      type: "Semantic",
      difficulty: "Red",
      level: 3,
      lesson_number: 3,
      title: "Semantic Annotation in Autonomous Systems",
      description: "Understanding how semantic annotation is used in autonomous systems.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
        id: 55,
        rank_id: 19,
        type: "Polygon",
        difficulty: "Green",
        level: 1,
        lesson_number: 1,
        title: "Introduction to Polygon Annotation",
        description: "Understanding the basics of polygon annotation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 56,
        rank_id: 19,
        type: "Polygon",
        difficulty: "Green",
        level: 1,
        lesson_number: 2,
        title: "Polygon Annotation Techniques",
        description: "Learning various techniques used in polygon annotation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 57,
        rank_id: 19,
        type: "Polygon",
        difficulty: "Green",
        level: 1,
        lesson_number: 3,
        title: "Polygon Annotation Applications",
        description: "Exploring real-world applications of polygon annotation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 58,
        rank_id: 20,
        type: "Polygon",
        difficulty: "Green",
        level: 2,
        lesson_number: 1,
        title: "Advanced Polygon Annotation Techniques",
        description: "Mastering advanced techniques in polygon annotation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 59,
        rank_id: 20,
        type: "Polygon",
        difficulty: "Green",
        level: 2,
        lesson_number: 2,
        title: "Polygon Annotation Challenges",
        description: "Challenges faced in polygon annotation and how to overcome them.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 60,
        rank_id: 20,
        type: "Polygon",
        difficulty: "Green",
        level: 2,
        lesson_number: 3,
        title: "Polygon Annotation Optimization",
        description: "Optimizing polygon annotation models for better performance.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 61,
        rank_id: 21,
        type: "Polygon",
        difficulty: "Green",
        level: 3,
        lesson_number: 1,
        title: "Polygon Annotation Mastery",
        description: "Mastering the art of polygon annotation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 62,
        rank_id: 21,
        type: "Polygon",
        difficulty: "Green",
        level: 3,
        lesson_number: 2,
        title: "Polygon Annotation Innovations",
        description: "Exploring innovative uses of polygon annotation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 63,
        rank_id: 21,
        type: "Polygon",
        difficulty: "Green",
        level: 3,
        lesson_number: 3,
        title: "Polygon Annotation in Autonomous Systems",
        description: "Understanding how polygon annotation is used in autonomous systems.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 64,
        rank_id: 22,
        type: "Polygon",
        difficulty: "Yellow",
        level: 1,
        lesson_number: 1,
        title: "Introduction to Polygon Labeling",
        description: "Understanding the basics of polygon labeling.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 65,
        rank_id: 22,
        type: "Polygon",
        difficulty: "Yellow",
        level: 1,
        lesson_number: 2,
        title: "Polygon Labeling Techniques",
        description: "Learning various techniques used in polygon labeling.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 66,
        rank_id: 22,
        type: "Polygon",
        difficulty: "Yellow",
        level: 1,
        lesson_number: 3,
        title: "Polygon Labeling Applications",
        description: "Exploring real-world applications of polygon labeling.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 67,
        rank_id: 23,
        type: "Polygon",
        difficulty: "Yellow",
        level: 2,
        lesson_number: 1,
        title: "Advanced Polygon Labeling Techniques",
        description: "Mastering advanced techniques in polygon labeling.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 68,
        rank_id: 23,
        type: "Polygon",
        difficulty: "Yellow",
        level: 2,
        lesson_number: 2,
        title: "Polygon Labeling Challenges",
        description: "Challenges faced in polygon labeling and how to overcome them.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 69,
        rank_id: 23,
        type: "Polygon",
        difficulty: "Yellow",
        level: 2,
        lesson_number: 3,
        title: "Polygon Labeling Optimization",
        description: "Optimizing polygon labeling models for better performance.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 70,
        rank_id: 24,
        type: "Polygon",
        difficulty: "Yellow",
        level: 3,
        lesson_number: 1,
        title: "Polygon Labeling Mastery",
        description: "Mastering the art of polygon labeling.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 71,
        rank_id: 24,
        type: "Polygon",
        difficulty: "Yellow",
        level: 3,
        lesson_number: 2,
        title: "Polygon Labeling Innovations",
        description: "Exploring innovative uses of polygon labeling.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 72,
        rank_id: 24,
        type: "Polygon",
        difficulty: "Yellow",
        level: 3,
        lesson_number: 3,
        title: "Polygon Labeling in Autonomous Systems",
        description: "Understanding how polygon labeling is used in autonomous systems.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
      },
      {
        id: 73,
        rank_id: 25,
        type: "Polygon",
        difficulty: "Red",
        level: 1,
        lesson_number: 1,
        title: "Introduction to Polygon Segmentation",
        description: "Understanding the basics of polygon segmentation.",
        passed: false,
        unlocked: false,
        total_points: 150,
        current_points: 0
        },
      {
      id: 74,
      rank_id: 25,
      type: "Polygon",
      difficulty: "Red",
      level: 1,
      lesson_number: 2,
      title: "Polygon Segmentation Techniques",
      description: "Learning various techniques used in polygon segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 75,
      rank_id: 25,
      type: "Polygon",
      difficulty: "Red",
      level: 1,
      lesson_number: 3,
      title: "Polygon Segmentation Applications",
      description: "Exploring real-world applications of polygon segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 76,
      rank_id: 26,
      type: "Polygon",
      difficulty: "Red",
      level: 2,
      lesson_number: 1,
      title: "Advanced Polygon Segmentation Techniques",
      description: "Mastering advanced techniques in polygon segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 77,
      rank_id: 26,
      type: "Polygon",
      difficulty: "Red",
      level: 2,
      lesson_number: 2,
      title: "Polygon Segmentation Challenges",
      description: "Challenges faced in polygon segmentation and how to overcome them.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 78,
      rank_id: 26,
      type: "Polygon",
      difficulty: "Red",
      level: 2,
      lesson_number: 3,
      title: "Polygon Segmentation Optimization",
      description: "Optimizing polygon segmentation models for better performance.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 79,
      rank_id: 27,
      type: "Polygon",
      difficulty: "Red",
      level: 3,
      lesson_number: 1,
      title: "Polygon Segmentation Mastery",
      description: "Mastering the art of polygon segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 80,
      rank_id: 27,
      type: "Polygon",
      difficulty: "Red",
      level: 3,
      lesson_number: 2,
      title: "Polygon Segmentation Innovations",
      description: "Exploring innovative uses of polygon segmentation.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      },
      {
      id: 81,
      rank_id: 27,
      type: "Polygon",
      difficulty: "Red",
      level: 3,
      lesson_number: 3,
      title: "Polygon Segmentation in Autonomous Systems",
      description: "Understanding how polygon segmentation is used in autonomous systems.",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0
      }
  ]);
};
