/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("lessons").del();
  await knex("lessons").insert([
    {
      id: 1,
      rank_id: 1,
      type: "Bounding Box",
      difficulty: "Green",
      level: 1,
      lesson_number: 1,
      title: "Image annotation",
      description:
        "This is the first lesson of image annotation for Bounding Box Green 1",
      passed: false,
      unlocked: true,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 2,
      rank_id: 1,
      type: "Bounding Box",
      difficulty: "Green",
      level: 1,
      lesson_number: 2,
      title: "Image annotation II",
      description:
        "This is the second lesson of image annotation for Bounding Box Green 1",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 3,
      rank_id: 1,
      type: "Bounding Box",
      difficulty: "Green",
      level: 1,
      lesson_number: 3,
      title: "Advanced image annotation",
      description:
        "This is the third lesson for Bounding Box Green 1 about advanced image annotation",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 4,
      rank_id: 2,
      type: "Bounding Box",
      difficulty: "Green",
      level: 2,
      lesson_number: 1,
      title: "Drawing boxes",
      description:
        "This is the first lesson for Bounding Box Green 2 about drawing boxes",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 5,
      rank_id: 2,
      type: "Bounding Box",
      difficulty: "Green",
      level: 2,
      lesson_number: 2,
      title: "BBG2L2",
      description:
        "This is the second lesson for Bounding Box Green 2 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 6,
      rank_id: 2,
      type: "Bounding Box",
      difficulty: "Green",
      level: 2,
      lesson_number: 3,
      title: "BBG2L3",
      description:
        "This is the third lesson for Bounding Box Green 2 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 7,
      rank_id: 3,
      type: "Bounding Box",
      difficulty: "Green",
      level: 3,
      lesson_number: 1,
      title: "BBG3L1",
      description:
        "This is the first lesson for Bounding Box Green 3 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 8,
      rank_id: 3,
      type: "Bounding Box",
      difficulty: "Green",
      level: 3,
      lesson_number: 2,
      title: "BBG3L2",
      description:
        "This is the second lesson for Bounding Box Green 3 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 9,
      rank_id: 3,
      type: "Bounding Box",
      difficulty: "Green",
      level: 3,
      lesson_number: 3,
      title: "BBG3L3",
      description:
        "This is the third lesson for Bounding Box Green 3 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 10,
      rank_id: 4,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 1,
      title: "BBY1L1",
      description:
        "This is the first lesson for Bounding Box Yellow 1 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 11,
      rank_id: 4,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 2,
      title: "BBY1L2",
      description:
        "This is the second lesson for Bounding Box Yellow 1 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
    {
      id: 12,
      rank_id: 4,
      type: "Bounding Box",
      difficulty: "Yellow",
      level: 1,
      lesson_number: 3,
      title: "BBY1L3",
      description:
        "This is the third lesson for Bounding Box Yellow 1 about ...",
      passed: false,
      unlocked: false,
      total_points: 150,
      current_points: 0,
    },
  ]);
};
